### ISSUE TITLE
Line

### ISSUE THREAD

**Issue by zamotany** [zamotany/react-slate#12]

**Comment by satya164** [comment]
I'm wondering how will we determine the width of screen, since `Hr` spans the screen width. Is it possible?

**Comment by zamotany** [comment]
`process.stdout.columns`, but we should accept the `width` as prop.

**Comment by satya164** [comment]
Nice. What happens when the terminal resizes?

**Comment by satya164** [comment]
I tried with Node REPL, but I had to restart the REPL to get the new column width after I resized the window.

**Comment by zamotany** [comment]
https://nodejs.org/api/tty.html#tty_event_resize

**Comment by zamotany** [comment]
Currently it doesn't make sense to implement this.
