### ISSUE TITLE
Improve public API for `render` function

### ISSUE THREAD

**Issue by zamotany** [zamotany/react-slate#57]
Rendering to terminal using TTY stream (no terminal enhancement):

```js
import { renderToTerminal } from 'react-slate';

renderToTerminal(<App />, process.stdout);
// or
renderToTerminal(<App />, process.stderr);
```

To overwrite console, hide cursor etc use `react-slate-utils`:

```js
import { renderToTerminal } from 'react-slate';
import { overwriteConsole, hideCursor } from 'react-slate-utils';

overwriteConsole(/* ... */);
hideCursor();

renderToTerminal(<App />, process.stdout);
```

For testing and other non-TTY streams:

```js
import { renderToString, renderToTerminal } from 'react-slate';
const snapshot = renderToString(<App />);
// or
renderToTerminal(<App />, process.stdout, { width: 40, height: 20 });
```

**Comment by satya164** [comment]
> `const forceUpdate = renderToTerminal(<App />, process.stdout);`

What is `forceUpdate`?

> `const frames = renderToFrames(<App />, { frames: 1 });`

`frames` is a string or array?

**Comment by zamotany** [comment]
`forceUpdate` just triggers re-render, there is no mounting/unmounting actually being done.

**Comment by satya164** [comment]
Would be nice follow the same API as ReactDOM and React Native, i.e. calling `renderToTerminal` on the same target again will trigger a re-render.
